### PR TITLE
Fix object authorization for union type

### LINKED ISSUE #25: using object auth on `union` types is failing
with `(KeyError) key :type not found`

in `Rajska.ObjectAuthorization.find_associations/2` there is 

```elixir
authorize(schema_node.type, selections ++ tail, resolution)
``` 

but union type do not have `:type` key (as the type of this type is dynamic)

any workarounds, pointers?

### PR DESCRIPTION
**Pull request by gabrielpra1**
Closes https://github.com/jungsoft/rajska/issues/25

### CODE REVIEW

**Comment by gabrielpra1** [comment]
Hey @moperacz, can you please check if this version now works for you?

In https://github.com/jungsoft/rajska/pull/26/commits/da2eba321c0400495e05bf5e0153f0e561cc8238 I also disabled the requirement for union types to define an `authorize` type, because we can just infer it from the underlying types. Does that make sense to you?

**Comment by moperacz** [comment]
yeah i will do this today TY!

**Comment by moperacz** [comment]
it is working perfectly now

**Comment by gabrielpra1** [comment]
Awesome! Version 1.0.1 with the fix is already available 😄

**Pull request merged**
